export const USER_NO_PROFILE = "https://res.cloudinary.com/dxygc9jz4/image/upload/v1724111299/bpd60ycdypstg6tzqmus.png"
export const colleges = [
  "St. Xavier’s College, Mumbai",
  "Narsee Monjee College of Commerce and Economics (NMCCE), Mumbai",
  "Mithibai College, Mumbai",
  "Jai Hind College, Mumbai",
  "KJ Somaiya College of Arts and Commerce, Mumbai",
  "Ramnarain Ruia College, Mumbai",
  "HR College of Commerce and Economics, Mumbai",
  "SIES College of Arts, Science & Commerce, Sion, Mumbai",
  "Sophia College for Women, Mumbai",
  "Grant Medical College, Mumbai",
  "Seth GS Medical College (KEM), Mumbai",
  "Tata Institute of Social Sciences (TISS), Mumbai",
  "Veermata Jijabai Technological Institute (VJTI), Mumbai",
  "Acharya Institute of Technology (AIT), Bangalore",
  "Aligarh Muslim University (AMU), Aligarh",
  "Amrita Vishwa Vidyapeetham Coimbatore (Amrita), Coimbatore",
  "Anna University (AU), Chennai",
  "B.M.S. Institute of Technology and Management (BMSIT), Bangalore",
  "BMS College of Engineering Bangalore (BMSCE), Bangalore",
  "Bangalore Institute of Technology (BIT), Bangalore",
  "Bannari Amman Institute of Technology (BIT), Erode",
  "Bharati Vidyapeeth Deemed University College of Engineering Pune (BVDUCOE), Pune",
  "Birla Institute of Technology and Science Pilani (BITS Pilani), Pilani",
  "CMR Institute of Technology Bangalore (CMRIT), Bangalore",
  "Chandigarh University (CU), Chandigarh",
  "Chitkara University (CU), Rajpura",
  "College of Engineering Pune (COEP), Pune",
  "D.Y. Patil College of Engineering Pune (DYPCOE), Pune",
  "Dayananda Sagar College of Engineering (DSCE), Bangalore",
  "Delhi Technological University (DTU), New Delhi",
  "Dr. Ambedkar Institute of Technology (AIT), Bangalore",
  "Dr. D.Y. Patil Institute of Technology Pune (DYPIoT), Pune",
  "East West Institute of Technology (EWIT), Bangalore",
  "Galgotias University (GU), Greater Noida",
  "Geethanjali College of Engineering and Technology (GCET), Hyderabad",
  "GITAM University (GITAM), Visakhapatnam",
  "Guru Gobind Singh Indraprastha University (GGSIPU), New Delhi",
  "Indian Institute of Information Technology Allahabad (IIIT Allahabad), Allahabad",
  "Indian Institute of Information Technology Bangalore (IIIT Bangalore), Bangalore",
  "Indian Institute of Information Technology Gwalior (IIIT Gwalior), Gwalior",
  "Indian Institute of Information Technology Kancheepuram (IIIT Kancheepuram), Kancheepuram",
  "Indian Institute of Information Technology Kottayam (IIIT Kottayam), Kottayam",
  "Indian Institute of Information Technology Lucknow (IIIT Lucknow), Lucknow",
  "Indian Institute of Information Technology Pune (IIIT Pune), Pune",
  "Indian Institute of Information Technology Sri City (IIIT Sri City), Sri City",
  "Indian Institute of Information Technology Vadodara (IIIT Vadodara), Vadodara",
  "Indian Institute of Science Bangalore (IISc Bangalore), Bangalore",
  "Indian Institute of Technology Bhubaneswar (IIT Bhubaneswar), Bhubaneswar",
  "Indian Institute of Technology Bombay (IIT Bombay), Mumbai",
  "Indian Institute of Technology Delhi (IIT Delhi), New Delhi",
  "Indian Institute of Technology Gandhinagar (IIT Gandhinagar), Gandhinagar",
  "Indian Institute of Technology Guwahati (IIT Guwahati), Guwahati",
  "Indian Institute of Technology Hyderabad (IIT Hyderabad), Hyderabad",
  "Indian Institute of Technology Indore (IIT Indore), Indore",
  "Indian Institute of Technology Jodhpur (IIT Jodhpur), Jodhpur",
  "Indian Institute of Technology Kanpur (IIT Kanpur), Kanpur",
  "Indian Institute of Technology Kharagpur (IIT Kharagpur), Kharagpur",
  "Indian Institute of Technology Madras (IIT Madras), Chennai",
  "Indian Institute of Technology Mandi (IIT Mandi), Mandi",
  "Indian Institute of Technology Patna (IIT Patna), Patna",
  "Indian Institute of Technology Roorkee (IIT Roorkee), Roorkee",
  "Institute of Chemical Technology Mumbai (ICT Mumbai), Mumbai",
  "International Institute of Information Technology Hyderabad (IIIT Hyderabad), Hyderabad",
  "Jadavpur University (JU), Kolkata",
  "Jamia Millia Islamia (JMI), New Delhi",
  "Jawaharlal Nehru Technological University Hyderabad (JNTUH), Hyderabad",
  "Jaypee Institute of Information Technology (JIIT), Noida",
  "JSS Science and Technology University (JSSSTU), Mysore",
  "K.J. Somaiya College of Engineering (KJSCE), Mumbai",
  "Kalinga Institute of Industrial Technology (KIIT), Bhubaneswar",
  "Kumaraguru College of Technology (KCT), Coimbatore",
  "Lovely Professional University (LPU), Jalandhar",
  "M.S. Engineering College (MSEC), Bangalore",
  "Mahatma Gandhi Institute of Technology (MGIT), Hyderabad",
  "Manipal Institute of Technology (MIT), Manipal",
  "MS Ramaiah Institute of Technology (MSRIT), Bangalore",
  "MVJ College of Engineering (MVJCE), Bangalore",
  "Nagarjuna College of Engineering and Technology (NCET), Bangalore",
  "National Institute of Engineering Mysore (NIE), Mysore",
  "National Institute of Technology Agartala (NIT Agartala), Agartala",
  "National Institute of Technology Arunachal Pradesh (NIT Arunachal Pradesh), Yupia",
  "National Institute of Technology Calicut (NIT Calicut), Kozhikode",
  "National Institute of Technology Durgapur (NIT Durgapur), Durgapur",
  "National Institute of Technology Jaipur (NIT Jaipur), Jaipur",
  "National Institute of Technology Kurukshetra (NIT Kurukshetra), Kurukshetra",
  "National Institute of Technology Meghalaya (NIT Meghalaya), Shillong",
  "National Institute of Technology Nagpur (NIT Nagpur), Nagpur",
  "National Institute of Technology Rourkela (NIT Rourkela), Rourkela",
  "National Institute of Technology Silchar (NIT Silchar), Silchar",
  "National Institute of Technology Surathkal (NIT Surathkal), Mangalore",
  "National Institute of Technology Trichy (NIT Trichy), Tiruchirappalli",
  "Netaji Subhas University of Technology (NSUT), New Delhi",
  "New Horizon College of Engineering (NHCE), Bangalore",
  "Nirma University (Nirma), Ahmedabad",
  "Noida Institute of Engineering and Technology (NIET), Greater Noida",
  "PES Institute of Technology South Campus (PESIT South), Bangalore",
  "PES University (PES), Bangalore",
  "PSG College of Technology (PSG Tech), Coimbatore",
  "R.V. College of Engineering Bangalore (RVCE), Bangalore",
  "Rajarajeswari College of Engineering (RRCE), Bangalore",
  "Reva University, Bangalore",
  "Sardar Vallabhbhai National Institute of Technology (SVNIT), Surat",
  "Sathyabama Institute of Science and Technology (Sathyabama), Chennai",
  "Shiv Nadar University (SNU), Greater Noida",
  "Siddaganga Institute of Technology (SIT), Tumkur",
  "Sikkim Manipal Institute of Technology (SMIT), Sikkim",
  "Sri Krishna Institute of Technology (SKIT), Bangalore",
  "SRM Institute of Science and Technology (SRMIST), Chennai",
  "SSN College of Engineering (SSN), Chennai",
  "Symbiosis Institute of Technology (SIT), Pune",
  "Tata Institute of Fundamental Research (TIFR), Mumbai",
  "Thapar Institute of Engineering and Technology (TIET), Patiala",
  "Vasavi College of Engineering Hyderabad (VCE), Hyderabad",
  "Vel Tech Rangarajan Dr. Sagunthala R&D Institute of Science and Technology (Vel Tech), Chennai",
  "Vellore Institute of Technology (VIT), Vellore",
  "Vidyavardhaka College Of Engineering (VVCE), Mysore",
  "Vignan's Foundation for Science, Technology, and Research (VFSTR), Guntur",
  "Visvesvaraya National Institute of Technology Nagpur (VNIT Nagpur), Nagpur",
  "Yeshwantrao Chavan College of Engineering Nagpur (YCCE Nagpur), Nagpur",
  "KC College Higher educational institution in Mumbai, Maharashtra",
  "Lady Shri Ram College for Women (LSR), Delhi",
  "Miranda House, Delhi",
  "Hindu College, Delhi",
  "Hansraj College, Delhi",
  "Shri Ram College of Commerce (SRCC), Delhi",
  "Christ University, Bangalore",
  "Loyola College, Chennai",
  "Presidency College, Chennai",
  "Fergusson College, Pune",
  "St. Stephen’s College, Delhi",
  "Maulana Azad Medical College (MAMC), Delhi",
  "Christian Medical College (CMC), Vellore",
  "Kasturba Medical College (KMC), Manipal",
  "All India Institute of Medical Sciences (AIIMS), Delhi",
  "Jawaharlal Institute of Postgraduate Medical Education and Research (JIPMER), Puducherry",
  "Banaras Hindu University (BHU), Varanasi",
  "Jamia Hamdard, Delhi"
];


// list of branches with shortform in brackets
export const branches = [
  // Engineering & Technology
  "Bachelor of Technology in Agricultural Engineering",
  "Master of Technology in Agricultural Engineering",
  "Diploma in Agricultural Engineering",

  "Bachelor of Technology in Aeronautical Engineering",
  "Master of Technology in Aeronautical Engineering",

  "Bachelor of Technology in Biomedical Engineering",
  "Master of Technology in Biomedical Engineering",

  "Bachelor of Technology in Biotechnology",
  "Master of Technology in Biotechnology",

  "Bachelor of Technology in Chemical Engineering",
  "Master of Technology in Chemical Engineering",

  "Bachelor of Technology in Computer Science Engineering",
  "Master of Technology in Computer Science Engineering",

  "Bachelor of Technology in Computer Science and Business Systems",

  "Bachelor of Technology in Electrical Engineering",
  "Master of Technology in Electrical Engineering",

  "Bachelor of Technology in Electronics and Communication Engineering",
  "Master of Technology in Electronics and Communication Engineering",

  "Bachelor of Technology in Food Technology",
  "Master of Technology in Food Technology",

  "Bachelor of Technology in Information Technology",
  "Master of Technology in Information Technology",

  "Bachelor of Technology in Marine Engineering",

  "Bachelor of Technology in Mechanical Engineering",
  "Master of Technology in Mechanical Engineering",
  "Diploma in Mechanical Engineering",

  "Bachelor of Technology in Metallurgical and Materials Engineering",
  "Master of Technology in Metallurgical and Materials Engineering",

  "Bachelor of Technology in Mining Engineering",

  "Bachelor of Technology in Production Engineering",
  "Master of Technology in Production Engineering",

  "Bachelor of Technology in Textile Technology",
  "Diploma in Textile Technology",

  // Computer & IT
  "Bachelor of Computer Applications",
  "Master of Computer Applications",
  "Bachelor of Science in Computer Science",
  "Master of Science in Computer Science",
  "Bachelor of Science in Information Technology",
  "Diploma in Web Development",
  "Diploma in App Development",
  "Diploma in Cyber Security",

  // Science
  "Bachelor of Science in Physics",
  "Master of Science in Physics",
  "Bachelor of Science in Chemistry",
  "Master of Science in Chemistry",
  "Bachelor of Science in Biology",
  "Master of Science in Biology",
  "Bachelor of Science in Mathematics",
  "Master of Science in Mathematics",
  "Bachelor of Statistics",
  "Master of Statistics",

  // Medical & Paramedical
  "Bachelor of Medicine and Bachelor of Surgery (MBBS)",
  "Bachelor of Dental Surgery (BDS)",
  "Bachelor of Ayurvedic Medicine and Surgery (BAMS)",
  "Bachelor of Homeopathic Medicine and Surgery (BHMS)",
  "Bachelor of Physiotherapy (BPT)",
  "Bachelor of Science in Nursing",
  "Master of Science in Nursing",
  "Bachelor of Pharmacy",
  "Master of Pharmacy",
  "Diploma in Pharmacy",
  "Diploma in Medical Lab Technology (DMLT)",
  "Bachelor of Medical Lab Technology (BMLT)",

  // Commerce & Business
  "Bachelor of Commerce in General Studies",
  "Bachelor of Commerce in Banking and Insurance",
  "Bachelor of Commerce in Accounting and Finance",
  "Master of Commerce",
  "Bachelor of Business Administration",
  "Master of Business Administration / Post Graduate Diploma in Management",
  "Chartered Accountancy",
  "Company Secretary",

  // Arts & Humanities
  "Bachelor of Arts in Economics",
  "Bachelor of Arts in English",
  "Bachelor of Arts in Political Science",
  "Bachelor of Arts in History",
  "Bachelor of Arts in Sociology",
  "Bachelor of Arts in Psychology",
  "Master of Arts in Economics",
  "Master of Arts in English",
  "Master of Arts in Political Science",
  "Master of Arts in History",
  "Master of Arts in Sociology",
  "Master of Arts in Psychology",
  "Bachelor of Social Work",
  "Master of Social Work",

  // Design & Media
  "Bachelor of Design",
  "Master of Design",
  "Bachelor of Mass Media / Bachelor of Arts in Multimedia and Mass Communication",
  "Bachelor of Journalism and Mass Communication",
  "Master of Journalism and Mass Communication",
  "Diploma in Animation",
  "Diploma in Graphic Design",
  "Diploma in UI/UX Design",
  "Diploma in VFX",

  // Law
  "Bachelor of Law (LLB)",
  "Bachelor of Arts and Bachelor of Law (BA LLB)",
  "Bachelor of Business Administration and Bachelor of Law (BBA LLB)",
  "Master of Law (LLM)",

  // Hotel Management & Tourism
  "Bachelor of Hotel Management",
  "Master of Hotel Management",
  "Bachelor of Travel and Tourism Management",

  // Others
  "Diploma in Digital Marketing",
  "Diploma in Foreign Languages (French)",
  "Diploma in Foreign Languages (German)",
  "Diploma in Foreign Languages (Spanish)"
];

export const ChatEventEnums = {
    CONNECTED_EVENT: "connected",
    DISCONNECT_EVENT: "disconnect",
    JOIN_CHAT_EVENT: "joinChat",
    NEW_CHAT_EVENT: "newChat",
    TYPING_EVENT: "typing",
    STOP_TYPING_EVENT: "stopTyping",
    MESSAGE_RECEIVED_EVENT: "messageReceived",
    LEAVE_CHAT_EVENT: "leaveChat",
    UPDATE_GROUP_NAME_EVENT: "updateGroupName",
    MESSAGE_DELETE_EVENT: "messageDeleted",
    MESSAGE_READ_EVENT: "messageRead"
}
